INSERT INTO players (id, name, nickname)
VALUES
('nhle', 'Nam Hoang Le', 'The Breaker'),
('bvphan', 'Binh Van Phan', 'Spin Master'),
('tttran', 'Tuyen Trung Tran', 'Silent Cue'),
('atvo', 'An Tien Vo', 'The Sharp Shooter'),
('bvqhuynh', 'Binh Van Quoc Huynh', 'Ice Man'),
('dple', 'Duy Phi Le', 'Smooth Stroke'),
('hnnguyen', 'Hung Ngoc Nguyen', 'The Tactician'),
('hqnguyen', 'Hieu Quang Nguyen', 'The Precisionist'),
('hqtran', 'Huy Quang Tran', 'Rack Reaper'),
('ltnguyen', 'Liem Thanh Nguyen', 'Cue Master'),
('mbnguyen', 'Minh Binh Nguyen', 'Rack Slayer'),
('qanguyen', 'Quoc Anh Nguyen', 'Angle Artist'),
('shvu', 'Son Hoang Vu', 'The Dominator'),
('thnguyen', 'Thien Hoang Nguyen', 'Cue Terminator'),
('tmdo', 'Tuan Minh Do', 'Pocket Predator'),
('lvluu', 'Loi Van Luu', 'The Dominator'),
('dxnguyen', 'Dung Xuan Nguyen', 'Ice Veins'),
('lhpham', 'Long Hoang Pham', NULL),
('benvphan', 'Ben Van Phan', NULL),
('ewilton', 'Eric Wilton', NULL),
('dqtrinh', 'Duy Quang Trinh', NULL),
('tuanttran', 'Tuan Thanh Tran', NULL);